name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        
    - name: Install dependencies
      working-directory: ./frontend
      run: npm ci
      
    - name: Run linter
      working-directory: ./frontend
      run: npm run lint
      
    - name: Build the application
      working-directory: ./frontend
      run: npm run build  

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and tag Docker image
      run: |
        IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/react-docker-ci
        TAG=latest
        docker build -t $IMAGE_NAME:$TAG .

    - name: Push Docker image
      run: |
        IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/react-docker-ci
        TAG=latest
        docker push $IMAGE_NAME:$TAG
